### ISSUE TITLE
Error when trying to compile proto file

### ISSUE THREAD

**Issue by bretwalker** [allegro/php-protobuf#8] opened 2013-09-13 01:38 UTC
I get the following error when trying to compile a [proto file from Google](https://developers.google.com/transit/gtfs-realtime/gtfs-realtime-proto):

>Proto file missformed

**Comment by aris** [comment] 2015-01-10 10:33
Hi,

I have tried to parse https://raw.githubusercontent.com/xemul/criu/master/protobuf/rpc.proto
The errors caused by:
1. Parsing semicolon or ;
2. Parsing /* comment */ comment

**Comment by hebrew878** [comment] 2015-07-06 17:00
Proto file missformed   here also https://github.com/egirault/googleplay-api/raw/master/googleplay.proto

**Comment by tonyliu-minted** [comment] 2016-01-29 23:35
I also encounter the same error. Have to replace all the block comments with line comments.

**Comment by keyboard1989** [comment] 2016-05-21 10:08
I also encounter the same question when parse openrtb.proto https://github.com/google/openrtb/blob/master/openrtb-core/src/main/protobuf/openrtb.proto

**Comment by hjagodzinski** [comment] 2016-07-18 06:34
Fixed in #74.

**Closed by hjagodzinski** 2016-07-18 06:34 UTC
